version: "3.8"

services:
  db:
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 10
      interval: 3s
      timeout: 30s
    restart: always

  phpmyadmin:
    image: phpmyadmin
    container_name: my-php-myadmin
    ports:
      - "8081:80"
    restart: always

    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_USERNAME: salma
      SPRING_DATASOURCE_PASSWORD: 1234

  backend:
    image: dent-backend
    container_name: dent-backend-app
    build:
      context: ./Dent
      dockerfile: Dockerfile
    ports:
      - "8083:8082"
    restart: always

    depends_on:
      db:
        condition: service_healthy
  frontend:
    image: dent-frontend
    container_name: dent-frontend-app
    build:
      context: ./dentFront
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always

    depends_on:
      db:
        condition: service_healthy
